[package]
org = "nuvindu"
name = "create_orders"
version = "0.1.0"
distribution = "2201.11.0"

[[dependency]]
org = "ballerinax"
name = "shopify"
version = "1.0.0"
repository = "local"

[build-options]
observabilityIncluded = true
